version: "3.7"

services:
  app:
    build: ./
    ports: 
      - "3001:3001"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "db_b_e_course"

    volumes: 
      - ./src/db/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
    expose:
      - "5432:5432"
    ports: 
      - "5432:5432"