version: "3.7"

services:
  app:
    build: ./
    environment:
      PORT: 3001
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: backend_course
    ports: 
      - "3001:3001"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: backend_course
    volumes: 
      - ./src/db/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
    expose:
      - "5432:5432"
    ports: 
      - "5432:5432"